### ISSUE TITLE
crash issue with merging

### ISSUE THREAD

**Issue by popcorn9499** [sandreas/m4b-tool#113]
Loving this program its fast and does the job I want usually. however recently with some tracks that refuse to get processed. 

I am currently running m4b-tool 0.4.2
ffmpeg version n4.3.1

The log I got was this

```
[popcorn9499@file-server-1 123.m4b]$ /usr/bin/m4b-tool merge --adjust-for-ipod './'
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac
Invalid format string (no match or invalid pattern <#(?P<H>[0-9]+)\:(?P<M>[0-9]+)\:(?P<S>[0-9]+)\.(?P<L>[0-9]+)#>)
an error occured, that has not been caught:
Array
(
    [type] => 512
    [message] => Failed to save key "streaminfo.e2cb9e8ee14e904c813fcfd8765e405007f2ee5cdee563f9e956ca8ff6fb6255" (string)
    [file] => phar:///usr/bin/m4b-tool/vendor/symfony/cache/CacheItem.php
    [line] => 197
)
```

So then I tried running it with -vvv to give you the most debug information

```
popcorn9499@file-server-1 123.m4b]$ /usr/bin/m4b-tool -vvv merge './'
ffmpeg -hide_banner -codecs
determine highest available audio codec
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac
== load input files ==
reading metadata and streaminfo for file /mnt/Internal/Raid6/tmp/ProcessAudiobooks/123.m4b/1 - Painted Ladies.mp3
ffmpeg -hide_banner -i "/mnt/Internal/Raid6/tmp/ProcessAudiobooks/123.m4b/1 - Painted Ladies.mp3" -f ffmetadata -
;FFMETADATA1
encoder=Lavf58.45.100

[mp3 @ 0x55b597ecb740] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/mnt/Internal/Raid6/tmp/ProcessAudiobooks/123.m4b/1 - Painted Ladies.mp3':
  Duration: 01:05:21.07, start: 0.000000, bitrate: 96 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 96 kb/s
Output #0, ffmetadata, to 'pipe:':
  Metadata:
    encoder         : Lavf58.45.100
Stream mapping:
Press [q] to stop, [?] for help
size=       0kB time=-577014:32:22.77 bitrate=N/A speed=N/A    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded 

ffmpeg -hide_banner -i "/mnt/Internal/Raid6/tmp/ProcessAudiobooks/123.m4b/1 - Painted Ladies.mp3" -f null -
++++

[mp3 @ 0x563df868c740] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/mnt/Internal/Raid6/tmp/ProcessAudiobooks/123.m4b/1 - Painted Ladies.mp3':
  Duration: 01:05:21.07, start: 0.000000, bitrate: 96 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 96 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_s16le
size=N/A time=01:05:21.05 bitrate=N/A speed=1.13e+03x    
video:0kB audio:675464kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

searching for cover in .
using cover  ./cover.jpg
searching for description.txt in .
checking file ./description.txt, realpath: 
file description.txt not found or too big
skip cover extraction, file ./cover.jpg already exists - use --force to overwrite
preparing conversion with 1 simultaneous job, please wait...
   0 remaining /    1 total, preparing next task |
could not convert /mnt/Internal/Raid6/tmp/ProcessAudiobooks/123.m4b/1 - Painted Ladies.mp3 to -tmpfiles/1-1 - Painted Ladies-finished.m4b
trace: #0 phar:///usr/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(479): M4bTool\Command\MergeCommand->convertInputFiles()
#1 phar:///usr/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(362): M4bTool\Command\MergeCommand->processInputFiles()
#2 phar:///usr/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(194): M4bTool\Command\MergeCommand->processFiles()
#3 phar:///usr/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
#4 phar:///usr/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run()
#5 phar:///usr/bin/m4b-tool/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///usr/bin/m4b-tool/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun()
#7 phar:///usr/bin/m4b-tool/bin/m4b-tool.php(32): Symfony\Component\Console\Application->run()
#8 /usr/bin/m4b-tool(10): require('phar:///usr/bin...')
#9 {main}
an error occured, that has not been caught:
Array
(
    [type] => 512
    [message] => Failed to save key "streaminfo.e2cb9e8ee14e904c813fcfd8765e405007f2ee5cdee563f9e956ca8ff6fb6255" (string)
    [file] => phar:///usr/bin/m4b-tool/vendor/symfony/cache/CacheItem.php
    [line] => 197
)
```

If I can provide any additional information I gladly will. If you would like I can potentially send a copy of the mp3s in question which refuse to convert if that will help.

Anyways happy holidays and thanks for the nice software

**Comment by sandreas** [comment]
Well, since it has been a very long time since the latest stable release, it would be great, if you try the latest pre-release. There should be A LOT of improvements and fixes and it is already stable enough for all day use (i use it myself since a pretty long time now). I'm planning to release the next stable release for a few month now but i just did not have the time (for documentation, brew updates, etc.).

**Comment by popcorn9499** [comment]
The latest pre release I saw was still a year out of date however I gave it a shot.

So it functioned correctly for the most part after I added the output file to the new application
```
123.m4b]# docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool merge ./ --output-file ./temp.m4b
PHP Warning:  file_put_contents(): Filename cannot be empty in phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php on line 226
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => file_put_contents(): Filename cannot be empty
    [file] => phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php
    [line] => 226
)
```

So I figured may as well since then you should have most if not all of the debug information required

```
123.m4b]# docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool merge -vvv  ./ --output-file ./temp.m4b
'ffmpeg' '-hide_banner' '-version'
== load input files ==
searching for cover in .
using cover ./cover.jpg
skip cover extraction, file ./cover.jpg already exists - use --force to overwrite
preparing conversion with 1 simultaneous job, please wait...
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './1 - Painted Ladies.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/1-converting.m4b'
   4 remaining /    5 total, preparing next task \'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './2 - Painted Ladies.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/2-converting.m4b'
   4 remaining /    5 total -                     'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './3 - Painted Ladies.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/3-converting.m4b'
   3 remaining /    5 total /                     'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './4 - Painted Ladies.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/4-converting.m4b'
   2 remaining /    5 total -                     'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './5 - Painted Ladies.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/5-converting.m4b'
   0 remaining /    5 total, preparing next task |
using cover ./cover.jpg
merging 5 files into /tmp/m4b-tool/tmp_temp.m4b, this can take a while
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-f' 'concat' '-safe' '0' '-vn' '-i' '/tmp/m4b-tool/tmp_temp.m4b.listing.txt' '-max_muxing_queue_size' '9999' '-c' 'copy' '-f' 'mp4' '/tmp/m4b-tool/tmp_temp.m4b'
improving tags...
==> trying improver Ffmetadata
ffmetadata.txt not found - tags not improved


==> trying improver ChaptersTxt
chapters.txt not found - tags not improved


==> trying improver ChaptersFromFileTracks
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/1-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/tmp/m4b-tool/1-finished.m4b'
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/2-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/tmp/m4b-tool/2-finished.m4b'
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/3-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/tmp/m4b-tool/3-finished.m4b'
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/4-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/tmp/m4b-tool/4-finished.m4b'
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/5-finished.m4b' '-f' 'ffmetadata' '-'
'mp4info' '/tmp/m4b-tool/5-finished.m4b'
chapter count changed from 0 to 5


==> trying improver OpenPackagingFormat
metadata.opf not found - tags not improved


==> trying improver AudibleTxt
no audible.txt found - tags not improved


==> trying improver AudibleJson
no audible.json found - tags not improved


==> trying improver M4bToolJson
m4b-tool.json not found - tags not improved


==> trying improver Description
description.txt not found - tags not improved


==> trying improver ContentMetadataJson
content_metadata_*.json not found - tags not improved


==> trying improver AudibleChaptersJson
content_metadata_*.json not found - tags not improved
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' '/tmp/m4b-tool/tmp_temp.m4b' '-vn' '-c:a' 'copy' '-f' 'crc' '-'
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/tmp_temp.m4b' '-af' 'silencedetect=noise=-30dB:d=1.75' '-f' 'null' '-'
running silence detection for file /tmp/m4b-tool/tmp_temp.m4b with min length 00:00:01.750
silence detection finished


==> trying improver AdjustTooLongChapters
no chapter length adjustment required (max chapter length not provided or empty chapter list)


==> trying improver InputOptions
input options improved the following 2 properties:
        encoder: <empty> => m4b-tool
          cover: <empty> => ./cover.jpg


'ffmpeg' '-hide_banner' '-i' './1 - Painted Ladies.mp3' '-f' 'ffmetadata' '-'
tagFile - filename: /tmp/m4b-tool/tmp_temp.m4b
full tag: {"encoder":"m4b-tool","title":"Painted Ladies 01-05","artist":"Robert B. Parker","genre":"Fiction","album":"Painted Ladies","year":{"date":"2010-01-01 00:00:00.000000","timezone_type":3,"timezone":"UTC"},"track":"01","cover":".\/cover.jpg","comment":"Read by Joe Mantegna","copyright":"2010","type":2,"publisher":"Random House Audio"}
'mp4tags' '-help'
'mp4tags' '-A' 'Painted Ladies' '-a' 'Robert B. Parker' '-t' '01' '-s' 'Painted Ladies 01-05' '-g' 'Fiction' '-y' '2010' '-c' 'Read by Joe Mantegna' '-C' '2010' '-E' 'm4b-tool' '-i' '2' '/tmp/m4b-tool/tmp_temp.m4b'
'mp4chaps' '-i' '/tmp/m4b-tool/tmp_temp.m4b'
'mp4art' '--remove' '--art-any' '/tmp/m4b-tool/tmp_temp.m4b'
'mp4art' '--add' './cover.jpg' '/tmp/m4b-tool/tmp_temp.m4b'
tagged file tmp_temp.m4b (artist: Robert B. Parker, name: Painted Ladies 01-05, chapters: 5)
moved temporary tmp_temp.m4b to ./temp.m4b
PHP Warning:  file_put_contents(): Filename cannot be empty in phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php on line 226
successfully merged 5 files to ./temp.m4b
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => file_put_contents(): Filename cannot be empty
    [file] => phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php
    [line] => 226
)
```


However overall it outputed a m4b and the m4b appears to be playable so I would call that an improvement.

**Comment by sandreas** [comment]
Great, thanks for the detailed report. I'll fix this minor issue in the next pre-release. This seems to be a little hickup with my latest experiments, which should not affect any other feature.

**Comment by popcorn9499** [comment]
If you need any help or just want a copy of the files which caused that issue let me know I will try to respond as quickly as I can.
