### ISSUE TITLE
Could not load musicbrainz record for id: 1d255b6c-8c89-41e0-a245-04904031caa0

### ISSUE THREAD

**Issue by dmuiX** [sandreas/m4b-tool#118]
Hi Andreas,

Found another Bug. But I don't know if its just this particular id that is just not wokring. Have nothing else to test actually.
Here are the outputs:

```
FOLDER=Die\ Dr3i\ -\ Das\ Seeungeheuer
ID=1d255b6c-8c89-41e0-a245-04904031caa0

m4b-tool chapters --merge-similar --first-chapter-offset 4000 --last-chapter-offset 3500 -m $ID $FOLDER.m4a -vvvv

'ffmpeg' '-hide_banner' '-version'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' 'Die Dr3i - Das Seeungeheuer.m4a' '-vn' '-c:a' 'copy' '-f' 'crc' '-'

In MusicBrainzChapterParser.php line 69:

  [Exception]
  Could not load musicbrainz record for id: 1d255b6c-8c89-41e0-a245-04904031caa0


Exception trace:
  at phar:///usr/local/bin/m4b-tool/src/library/Parser/MusicBrainzChapterParser.php:69
 M4bTool\Parser\MusicBrainzChapterParser->loadRecordings() at phar:///usr/local/bin/m4b-tool/src/library/Command/ChaptersCommand.php:153
 M4bTool\Command\ChaptersCommand->execute() at phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/m4b-tool/bin/m4b-tool.php:44
 require() at /usr/local/bin/m4b-tool:10

chapters [--logfile [LOGFILE]] [--debug] [-f|--force] [--tmp-dir [TMP-DIR]] [--no-cleanup] [--no-cache] [--ffmpeg-threads [FFMPEG-THREADS]] [--platform-charset [PLATFORM-CHARSET]] [--ffmpeg-param [FFMPEG-PARAM]] [-a|--silence-min-length [SILENCE-MIN-LENGTH]] [-b|--silence-max-length [SILENCE-MAX-LENGTH]] [--max-chapter-length [MAX-CHAPTER-LENGTH]] [--epub [EPUB]] [--epub-restore] [--epub-dump] [--epub-ignore-chapters [EPUB-IGNORE-CHAPTERS]] [--epub-append-introduction] [-m|--musicbrainz-id MUSICBRAINZ-ID] [-s|--merge-similar] [-o|--output-file [OUTPUT-FILE]] [--adjust-by-silence] [--find-misplaced-chapters [FIND-MISPLACED-CHAPTERS]] [--find-misplaced-offset [FIND-MISPLACED-OFFSET]] [--find-misplaced-tolerance [FIND-MISPLACED-TOLERANCE]] [--no-chapter-numbering] [--no-chapter-import] [--chapter-pattern [CHAPTER-PATTERN]] [--chapter-replacement [CHAPTER-REPLACEMENT]] [--chapter-remove-chars [CHAPTER-REMOVE-CHARS]] [--first-chapter-offset [FIRST-CHAPTER-OFFSET]] [--last-chapter-offset [LAST-CHAPTER-OFFSET]] [--] <input>

```

Same result for the merge command:
```

BIT=80
SR=48000

m4b-tool merge --cover=${FOLDER}/cover.jpg --jobs 4 --output-file="${FOLDER}_${BIT}_${SR}.m4b" --audio-format=m4a --audio-bitrate=$BIT --audio-samplerate=$SR -vvvv --max-chapter-length 300,350 --chapter-algo=grouping --force --musicbrainz-id=${ID} ./"${FOLDER}/"

'ffmpeg' '-hide_banner' '-codecs'
'ffmpeg' '-hide_banner' '-version'
Output file Die Dr3i - Das Seeungeheuer_80k_48000.m4b exists, but --force is present - overwrite file
== load input files ==
using cover Die Dr3i - Das Seeungeheuer/cover.jpg
skip cover extraction, a custom cover has been specified: Die Dr3i - Das Seeungeheuer/cover.jpg
preparing conversion with 4 simultaneous jobs, please wait...
   0 remaining /    1 total, preparing next task |
using cover Die Dr3i - Das Seeungeheuer/cover.jpg
only 1 file in merge list, copying file
improving tags...
==> trying improver Ffmetadata
ffmetadata.txt not found - tags not improved


==> trying improver ChaptersTxt
chapters.txt not found - tags not improved


==> trying improver ChaptersFromMusicBrainz
Could not load musicbrainz record for id: 1d255b6c-8c89-41e0-a245-04904031caa0
trace: #0 phar:///usr/local/bin/m4b-tool/src/library/Audio/Tag/ChaptersFromMusicBrainz.php(48): M4bTool\Parser\MusicBrainzChapterParser->loadRecordings()
#1 phar:///usr/local/bin/m4b-tool/src/library/Audio/Tag/TagImproverComposite.php(49): M4bTool\Audio\Tag\ChaptersFromMusicBrainz->improve(Object(M4bTool\Audio\Tag))
#2 phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php(851): M4bTool\Audio\Tag\TagImproverComposite->improve(Object(M4bTool\Audio\Tag))
#3 phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php(524): M4bTool\Command\MergeCommand->tagMergedFile(Object(SplFileInfo))
#4 phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php(423): M4bTool\Command\MergeCommand->processInputFiles()
#5 phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php(184): M4bTool\Command\MergeCommand->processFiles(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\MergeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/local/bin/m4b-tool/bin/m4b-tool.php(44): Symfony\Component\Console\Application->run()
#11 /usr/local/bin/m4b-tool(10): require('phar:///usr/loc...')
#12 {main}
```

**Comment by sandreas** [comment]
Thanks for reporting. Maybe they changed their API, I'll take a look.

**Comment by sandreas** [comment]
Should be fixed in the latest pre-release. Feedback would be great.

**Comment by sandreas** [comment]
Closing due to no further feedback.
