### ISSUE TITLE
"Could not convert..." using docker image

### ISSUE THREAD

**Issue by alsack** [sandreas/m4b-tool#197]
Using the docker image sandreas/m4b-tool:latest (pulled today 24 Sep 2022) I get the error "could not convert ./The_Long_Way_to_a_Small_Angry_Planet-01.mp3 to /tmp/m4b-tool/01-finished.m4b" when trying to merge files.  This had previously worked prior to pulling the latest image, and I see that a new image was pushed yesterday.  Unfortunately it doesn't appear that docker hub has any previous versions for me to roll back (https://hub.docker.com/r/sandreas/m4b-tool/tags).

Full debug output:

```
>m4b-tool merge -vv --jobs=3 --name="The Long Way to a Small Angry Planet" --artist="Becky Chambers" --series="Wayfarers" --series-part="1" . --output-file="The Long Way to a Small Angry Planet.m4b" --debug
m4b-tool development, OS: Linux (Welcome to Alpine Linux 3.14
Kernel \r on an \m (\l))
'ffmpeg' '-hide_banner' '-version'
== load input files ==
found 14 files to convert
The_Long_Way_to_a_Small_Angry_Planet-01.mp3
The_Long_Way_to_a_Small_Angry_Planet-02.mp3
The_Long_Way_to_a_Small_Angry_Planet-03.mp3
The_Long_Way_to_a_Small_Angry_Planet-04.mp3
The_Long_Way_to_a_Small_Angry_Planet-05.mp3
The_Long_Way_to_a_Small_Angry_Planet-06.mp3
The_Long_Way_to_a_Small_Angry_Planet-07.mp3
The_Long_Way_to_a_Small_Angry_Planet-08.mp3
The_Long_Way_to_a_Small_Angry_Planet-09.mp3
The_Long_Way_to_a_Small_Angry_Planet-10.mp3
The_Long_Way_to_a_Small_Angry_Planet-11.mp3
The_Long_Way_to_a_Small_Angry_Planet-12.mp3
The_Long_Way_to_a_Small_Angry_Planet-13.mp3
The_Long_Way_to_a_Small_Angry_Planet-14.mp3
searching for cover in .
using cover ./cover.jpg
skip cover extraction, file ./cover.jpg already exists - use --force to overwrite
preparing conversion with 3 simultaneous jobs, please wait...
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-01.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/01-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-02.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/02-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-03.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/03-converting.m4b'

  11 remaining /   14 total, preparing next task |'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-04.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/04-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-05.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/05-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-06.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/06-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-07.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/07-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-08.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/08-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-09.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/09-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-10.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/10-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-11.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/11-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-12.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/12-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-13.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/13-converting.m4b'
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' './The_Long_Way_to_a_Small_Angry_Planet-14.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/tmp/m4b-tool/14-converting.m4b'

   0 remaining /   14 total, preparing next task /
[30;41mcould not convert ./The_Long_Way_to_a_Small_Angry_Planet-01.mp3 to /tmp/m4b-tool/01-finished.m4b[39;49m
trace: #0 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(523): M4bTool\Command\MergeCommand->convertInputFiles()
#1 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(424): M4bTool\Command\MergeCommand->processInputFiles()
#2 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(185): M4bTool\Command\MergeCommand->processFiles()
#3 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
#4 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 phar:///usr/local/bin/m4b-tool-pre/bin/m4b-tool.php(52): Symfony\Component\Console\Application->run()
#8 /usr/local/bin/m4b-tool-pre(10): require('...')
#9 {main}
```

**Comment by Klench** [comment]
I am experiencing the same issue with docker running on both Linux and Mac. As mentioned by @alsack, it would be nice with available tags for image rollback.
Might the issue be `ffmpeg` not being available in the container?

**Comment by sandreas** [comment]
Yeah I'm sorry, this is currently experimental. I'll see what I can do today.

**Comment by sandreas** [comment]
@Klench @alsack 
Now fixed... every now and than I will push a dated tag, that I personally consider as *pretty* stable. 
```bash
docker pull sandreas/m4b-tool:2022-09-25
```
Documentation has to be updated, but there is already #187, so I close this.
