### ISSUE TITLE
Could not tag file with `m4b-tool split`

### ISSUE THREAD

**Issue by gazpachoking** [sandreas/m4b-tool#218]
Getting this error (which repeats for every file creating during the split command) when trying to split an m4b into chapters. I don't actually notice anything other than the wall of red logged during the command going wrong though, so maybe it can just be ignored.

```
could not tag file /temp/untagged/Adrian Tchaikovsky-Time-#1-Children of Time/001-1.m4b, error: Call to a member function contains() on null
#0 phar:///usr/local/bin/m4b-tool-pre/src/library/Audio/BinaryWrapper.php(265): M4bTool\Executables\Tone->writeTag()
#1 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/AbstractConversionCommand.php(260): M4bTool\Audio\BinaryWrapper->writeTag()
#2 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/SplitCommand.php(369): M4bTool\Command\AbstractConversionCommand->tagFile()
#3 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/SplitCommand.php(132): M4bTool\Command\SplitCommand->splitChapters()
#4 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\SplitCommand->execute()
#5 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 phar:///usr/local/bin/m4b-tool-pre/bin/m4b-tool.php(52): Symfony\Component\Console\Application->run()
#9 /usr/local/bin/m4b-tool-pre(10): require('...')
#10 {main}
```

**Comment by sandreas** [comment]
Please provide a full command and the `m4b-tool --version` output.

**Comment by gazpachoking** [comment]
Running inside a docker container. This is a different book, but I use the same command on them all.
```bash
m4b-tool-pre split '/temp/merged/1 - House of Earth and Blood/1 - House of Earth and Blood.m4b' --skip-cover --max-chapter-
length=3600,5400 '--output-dir=/temp/untagged/1 - House of Earth and Blood'
```
```bash
docker compose exec auto-m4b m4b-tool-pre --version
m4b-tool latest-178-gaeb8b2b
```

**Comment by gazpachoking** [comment]
Docker container is based on the official one here, but I've modified it to pull 0.1.3 of tone rather than 0.1.0. (I had the same problem on 0.1.0, was seeing if the latest version helped.)

**Comment by sandreas** [comment]
Confirmed. Misconception in `Tone` wrapper. Fix follows hopefully in the next days.
