### ISSUE TITLE
Call to a member function getStart() on array

### ISSUE THREAD

**Issue by jeff47** [sandreas/m4b-tool#264]
Hello,
I'm seeing this error when I try to run a batch process.

CLI:

```
m4b-tool merge -vvvv --jobs=2 --output-file="output/" --writer="O'Brian, Patrick" --batch-pattern="./%w/%s/%p - %n/" "./O'Brian, Patrick/"
```
where `m4b-tool` is aliased to:
```
docker run -it --rm -u 1001:1001 -v "$(pwd)":/mnt sandreas/m4b-tool:latest --audio-bitrate=64k --audio-samplerate=22050 --audio-profile=aac_he --audio-codec=libfdk_aac'
```

m4b-tool v0.5-prerelease-25-g81b9542

```
m4b-tool development, OS: Linux (Welcome to Alpine Linux 3.14
Kernel \r on an \m (\l))
== load input files ==
found 1 files to convert
searching for cover in ./O'Brian, Patrick/Aubrey-Maturin/21 - The Final Unfished Voyage of Jack Aubrey
using cover ./O'Brian, Patrick/Aubrey-Maturin/21 - The Final Unfished Voyage of Jack Aubrey/cover.jpg
skip cover extraction, file ./O'Brian, Patrick/Aubrey-Maturin/21 - The Final Unfished Voyage of Jack Aubrey/cover.jpg already exists - use --force to overwrite
### batch job 21/21 ###: preparing conversion with 2 simultaneous jobs, please wait...
   0 remaining /    1 total, preparing next task |
using cover ./O'Brian, Patrick/Aubrey-Maturin/21 - The Final Unfished Voyage of Jack Aubrey/cover.jpg
only 1 file in merge list, copying file
improving tags...
==> trying improver CueSheet
==== current tag ====
type             : 2

Empty tag fields : album, albumartist, artist, chapters, comment, copyright, cover, description, disk, disks, encoded-by, encoder, genre, grouping, language, longdesc, lyrics, name, performer, publisher, purchaseDate, sortAlbumArtist, sortWriter, sortalbum, sortartist, sortname, track, tracks, writer, year


==> trying improver Ffmetadata
ffmetadata.txt not found - tags not improved
==== current tag ====
- tag has not changed since the last improver


==> trying improver ChaptersTxt
chapters.txt not found - tags not improved
==== current tag ====
- tag has not changed since the last improver


==> trying improver ChaptersFromOverdrive
'ffmpeg' '-hide_banner' '-i' './O'\''Brian, Patrick/Aubrey-Maturin/21 - The Final Unfished Voyage of Jack Aubrey/01 AM21 - The Final Unfinished Voyage of Jack Aubrey.m4b' '-f' 'ffmetadata' '-'
no overdrive chapters found - tags not improved
==== current tag ====
- tag has not changed since the last improver


==> trying improver ChaptersFromFileTracks
'ffmpeg' '-hide_banner' '-i' '/tmp/m4b-tool/1-finished.m4b' '-f' 'ffmetadata' '-'
'tone' 'dump' '/tmp/m4b-tool/1-finished.m4b' '--format' 'json' '--query' '$.audio.duration'
==== current tag ====
chapters         
## total-duration:: 07:50:57.848
00:00:00.000 1
Empty tag fields : album, albumartist, artist, comment, copyright, cover, description, disk, disks, encoded-by, encoder, genre, grouping, language, longdesc, lyrics, name, performer, publisher, purchaseDate, sortAlbumArtist, sortWriter, sortalbum, sortartist, sortname, track, tracks, writer, year
chapter count changed from 0 to 1


==> trying improver MetadataJson
metadata.json loaded for tagging
Call to a member function getStart() on array
trace: #0 phar:///usr/local/bin/m4b-tool-pre/src/library/Executables/AbstractExecutable.php(179): M4bTool\Executables\AbstractExecutable::toChaptersTxt()
#1 phar:///usr/local/bin/m4b-tool-pre/src/library/Executables/Mp4v2Wrapper.php(107): M4bTool\Executables\AbstractExecutable->buildChaptersTxt()
#2 phar:///usr/local/bin/m4b-tool-pre/src/library/Audio/BinaryWrapper.php(235): M4bTool\Executables\Mp4v2Wrapper->buildChaptersTxt()
#3 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/AbstractCommand.php(506): M4bTool\Audio\BinaryWrapper->toMp4v2ChaptersFormat()
#4 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(858): M4bTool\Command\AbstractCommand->dumpTagAsLines()
#5 phar:///usr/local/bin/m4b-tool-pre/src/library/Audio/Tag/TagImproverComposite.php(92): M4bTool\Command\MergeCommand->M4bTool\Command\{closure}()
#6 phar:///usr/local/bin/m4b-tool-pre/src/library/Audio/Tag/TagImproverComposite.php(79): M4bTool\Audio\Tag\TagImproverComposite->dumpDebugInfo()
#7 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(926): M4bTool\Audio\Tag\TagImproverComposite->improve()
#8 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(538): M4bTool\Command\MergeCommand->tagMergedFile()
#9 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(430): M4bTool\Command\MergeCommand->processInputFiles()
#10 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(187): M4bTool\Command\MergeCommand->processFiles()
#11 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(388): M4bTool\Command\MergeCommand->execute()
#12 phar:///usr/local/bin/m4b-tool-pre/src/library/Command/MergeCommand.php(183): M4bTool\Command\MergeCommand->processBatchJobs()
#13 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
#14 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#15 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#16 phar:///usr/local/bin/m4b-tool-pre/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#17 phar:///usr/local/bin/m4b-tool-pre/bin/m4b-tool.php(52): Symfony\Component\Console\Application->run()
#18 /usr/local/bin/m4b-tool-pre(10): require('...')
#19 {main}
```

**Comment by sandreas** [comment]
I'll take a look tomorrow.

**Comment by sandreas** [comment]
@jeff47 

Before I go on, does your audio book folder contain a `*_metadata.json` file? If so, I'd probably need it to to reproduce...

**Comment by jeff47** [comment]
> @jeff47
> 
> Before I go on, does your audio book folder contain a `*_metadata.json` file? If so, I'd probably need it to to reproduce...

Nope, just the audio file and nothing else.

**Comment by sandreas** [comment]
> Nope, just the audio file and nothing else.

I'm still trying to reproduce this. I guess it might have something to do with using the `output` directory beneath the audiobook instead of having an `input` directory, e.g.:

```
├── input
│  └── "O'Brian, Patrick"
└── output
```

But I'll verify that.

**Comment by sandreas** [comment]
Reproduced it, I'll tell you as soon as I also fixed it.
