### ISSUE TITLE
PHP Fatal error: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Helper/HelperSet.php:104

### ISSUE THREAD

**Issue by parkr** [sandreas/m4b-tool#265]
Thanks for some great software! I'm having some trouble with `--musicbrainz-id` and was attempting to build from source. I don't have Docker and really don't want to install it / run it, so I'm working with `./build` on my machine.

Attempting to run `./build` on macOS shows the following exception. PHP 8.3.13 and Compose 2.8.2.

`tools/box.phar` appears to be incompatible with.. something.

```
Fatal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Helper/HelperSet.php:104
Stack trace:
#0 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Helper/HelperSet.php(21): KevinGH\Box\Application->KevinGH\Box\{closure}(8192, 'Return type of ...', 'phar:///private...', 104)
#1 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/composer/ClassLoader.php(414): include('phar:///private...')
#2 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/composer/ClassLoader.php(301): Composer\Autoload\includeFile('phar:///private...')
#3 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php(951): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/lib/KevinGH/Box/Application.php(115): Symfony\Component\Console\Application->getDefaultHelperSet()
#5 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php(88): KevinGH\Box\Application->getDefaultHelperSet()
#6 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/lib/KevinGH/Box/Application.php(38): Symfony\Component\Console\Application->__construct('Box', '2.7.5')
#7 phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/bin/box(18): KevinGH\Box\Application->__construct()
#8 /private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar(12): require('phar:///private...')
#9 {main} in phar:///private/tmp/m4b-tool-20241111-29505-wfq37b/tools/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Helper/HelperSet.php on line 21
```

```
$ php --version
PHP 8.3.13 (cli) (built: Oct 22 2024 18:39:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.13, Copyright (c), by Zend Technologies
$ composer --version
Composer version 2.8.2 2024-10-29 16:12:11
PHP version 8.3.13 (/opt/homebrew/Cellar/php/8.3.13_1/bin/php)
Run the "diagnose" command to get more detailed diagnostics output.
```

**Comment by parkr** [comment]
I think a new version of box might fix it: https://github.com/box-project/box/issues/562#issuecomment-1029966021

**Comment by parkr** [comment]
Yep, using a new version of Box (I used https://github.com/box-project/box/releases/tag/4.6.1), then changing `box.phar build` to `box.phar compile` fixed it for me.

**Comment by parkr** [comment]
And the musicbrainz-id fix was as simple as:

```diff
diff --git src/library/Command/MergeCommand.php src/library/Command/MergeCommand.php
index 40355c4..e8e6b20 100644
--- src/library/Command/MergeCommand.php
+++ src/library/Command/MergeCommand.php
@@ -881,7 +881,7 @@ class MergeCommand extends AbstractConversionCommand
             $mbChapterParser = new MusicBrainzChapterParser($mbId);
             $mbChapterParser->setCacheAdapter($this->cacheAdapter);
 
-            $tagImprover->add(new ChaptersFromMusicBrainz($this->chapterMarker, $this->chapterHandler, $mbChapterParser, $this->metaHandler->estimateDuration($this->outputFile)));
+            $tagImprover->add(new ChaptersFromMusicBrainz($this->chapterMarker, $this->chapterHandler, $mbChapterParser, $this->metaHandler->estimateDuration($outputTmpFile)));
         }
 ```

**Comment by parkr** [comment]
musicbrainz-id fix proposed here: https://github.com/sandreas/m4b-tool/pull/266

**Comment by sandreas** [comment]
@parkr First I would like to thank you for supporting the project. Today I took the time and created an experimental branch where I brought `m4b-tool` up to the latest dependencies (e.g. box, symfony, etc.).

I have to verify if this is working as expected or producing errors, but this is where it should go.

The branch can be tested at https://github.com/sandreas/m4b-tool/tree/symfony-upgrade-2024, please feel free to check it out and provide more information what works and what does not.

**Comment by parkr** [comment]
Built & tested -- it works great for me!

The only piece I'm confused about is why chapters from MusicBrainz end in a `(1)`:

```
==> trying improver ChaptersFromMusicBrainz
==== current tag ====
## total-duration:: 09:42:48.802
00:00:00.000 Chapter 1: The Worst Birthday (1)
00:18:31.926 Chapter 2: Dobby’s Warning (1)
00:39:36.345 Chapter 3: The Burrow (1)
01:08:40.404 Chapter 4: At Flourish and Blotts (1)
01:48:18.690 Chapter 5: The Whomping Willow (1)
02:24:45.763 Chapter 6: Gilderoy Lockhart (1)
02:55:25.702 Chapter 7: Mudbloods and Murmurs (1)
03:23:47.161 Chapter 8: The Deathday Party (1)
03:53:31.100 Chapter 9: The Writing on the Wall (1)
04:27:16.146 Chapter 10: The Rogue Bludger (1)
05:00:40.699 Chapter 11: The Duelling Club (1)
05:40:01.932 Chapter 12: The Polyjuice Potion (1)
06:16:12.325 Chapter 13: The Very Secret Diary (1)
06:52:50.371 Chapter 14: Cornelius Fudge (1)
07:20:07.137 Chapter 15: Aragog (1)
07:52:40.610 Chapter 16: The Chamber of Secrets (1)
08:32:25.336 Chapter 17: The Heir of Slytherin (1)
09:14:38.049 Chapter 18: Dobby’s Reward (1)
```

From https://musicbrainz.org/release/ffb8f930-6a5b-4adc-ad03-560cfd9e8701

Command:

```text
 ~/code/m4b-tool/dist/m4b-tool.phar merge *.mp3 --output-file Book2.m4b --jobs=8 --musicbrainz-id=ffb8f930-6a5b-4adc-ad03-560cfd9e8701 --cover=cover.jpg --debug
```
```

**Comment by sandreas** [comment]
> Built & tested -- it works great for me!

Great, thanks for the feedback. I'll look into this AND I found out something did not work with the covers - but this also might be something wrong with `tone` (I am using the latest `tone 0.1.9`, while `m4b-tool` currently is build with `0.1.7`)

**Comment by sandreas** [comment]
Next steps:

- [ ] switch `box` to composer instead of commiting the phar to `tools/box.phar`
- [ ] update `build` script to work with new box
- [ ] create github `release.yml` action to do releases automatically instead of uploading `pre-release` phars all the time
- [ ] create github `docker` action to publish a docker image for the latest version containing the latest specs

**Comment by sandreas** [comment]
@parkr 

Ok, I restructured the whole build process. Now it should all work by using `composer` with box (I have to update the documentation though). 

Would be great if you could try it out. 

I also created a github action for release to automatically build all release artifacts without needing a manual `pre-release` upload (which was a very bad solution in general). However, I hope I can publish `0.5.0` in the next days having a pipelined `m4b-tool`, `sandreas/m4b-tool:0.5.0` docker image and if possible also a `brew install m4b-tool` (that one is in the making). 

Thanks again for helping me forcing myself to do that - it has been a itching pain for the last YEARS ;)

**Comment by sandreas** [comment]
@parkr 
Done, `0.5.0` is out. Let's see what bounces back... documentation updates to come.

**Comment by parkr** [comment]
Hey, this looks great! Thanks so much for doing this and pushing out a new release. I have been traveling so haven't had time to use the new release yet but hope to in the coming days test it out. I can help with a Homebrew formula if you'd like. I believe it could download the latest phar release and symlink. It would depend on PHP IIUC, perhaps with a version constraint if needed.

**Comment by sandreas** [comment]
> I can help with a Homebrew formula if you'd like.

Thank you, this would be cool. I was hoping to use an automated release via https://github.com/marketplace/actions/homebrew-releaser but I have to check if this action is trustworthy, because it uses the secret github token to add content to another repository.

Unfortunately I ditched my old MacBook Pro years ago in favour of a Linux notebook, but maybe I could use coreboot to setup a modern supported macOS... we'll see. For now I have to update the brew formula manually. The repository is https://github.com/sandreas/homebrew-tap/ if you consider to submit a PR :-)

**Comment by parkr** [comment]
I updated the homebrew formula with `brew edit m4b-tool`, and then installed it. I ran `m4b-tool merge *.mp3 --output-file Book7.m4b --jobs=8 --cover=amazon-cover.jpg --debug` and everything looked perfect. If I added the MusicBrainz argument `--musicbrainz-id=c95b2567-f609-4cfa-83d4-80d23a60f817` then it would add the `(1)` to the chapters.

<details>

<summary>MusicBrainz Debug Output</summary>

```
==> trying improver ChaptersFromMusicBrainz
==== current tag ====
## total-duration:: 24:01:31.078
00:00:00.000 Chapter 1: The Dark Lord Ascending (1)
00:26:17.926 Chapter 2: In Memoriam (1)
00:56:41.879 Chapter 3: The Dursleys Departing (1)
01:21:50.965 Chapter 4: The Seven Potters (1)
02:00:54.504 Chapter 5: Fallen Warrior (1)
02:45:10.083 Chapter 6: The Ghoul In Pyjamas (1)
03:31:48.956 Chapter 7: The Will of Albus Dumbledore (1)
04:18:26.162 Chapter 8: The Wedding (1)
05:03:42.115 Chapter 9: A Place to Hide (1)
05:32:58.588 Chapter 10: Kreacher’s Tale (1)
06:21:57.167 Chapter 11: The Bribe (1)
07:02:57.800 Chapter 12: Magic is Might (1)
07:45:41.579 Chapter 13: The Muggle-Born Registration Commission (1)
08:27:41.465 Chapter 14: The Thief (1)
08:56:43.898 Chapter 15: The Goblin’s Revenge (1)
09:44:53.197 Chapter 16: Godric’s Hollow (1)
10:21:24.830 Chapter 17: Bathilda’s Secret (1)
11:01:54.876 Chapter 18: The Life and Lies of Albus Dumbledore (1)
11:25:35.762 Chapter 19: The Silver Doe (1)
12:12:12.875 Chapter 20: Xenophilius Lovegood (1)
12:42:43.228 Chapter 21: The Tale of the Three Brothers (1)
13:16:59.941 Chapter 22: The Deathly Hallows (1)
13:57:31.574 Chapter 23: Malfoy Manor (1)
14:57:45.327 Chapter 24: The Wandmaker (1)
15:46:19.573 Chapter 25: Shell Cottage (1)
16:16:20.219 Chapter 26: Gringotts (1)
17:04:13.265 Chapter 27: The Final Hiding Place (1)
17:23:53.231 Chapter 28: The Missing Mirror (1)
17:55:35.944 Chapter 29: The Lost Diadem (1)
18:26:13.163 Chapter 30: The Sacking of Severus Snape (1)
19:01:03.009 Chapter 31: The Battle of Hogwarts (1)
19:58:17.122 Chapter 32: The Elder Wand (1)
20:40:39.035 Chapter 33: The Prince’s Tale (1)
21:43:23.441 Chapter 34: The Forest Again (1)
22:12:51.207 Chapter 35: King’s Cross (1)
22:52:41.853 Chapter 36: The Flaw in the Plan (1)
23:49:44.992 Epilogue: Nineteen Years Later (1)
```

</details>

Looks great to me though! Working well on my MBP. I'll submit that patch to you here: https://github.com/sandreas/homebrew-tap/pull/4

**Comment by parkr** [comment]
Not that you need it since switching to Linux, but Linuxbrew is available for testing: https://docs.brew.sh/Homebrew-on-Linux

**Comment by sandreas** [comment]
> I updated the homebrew formula with brew edit m4b-tool, and then installed it.

Awesome thank you. Already merged.

> If I added the MusicBrainz argument --musicbrainz-id=c95b2567-f609-4cfa-83d4-80d23a60f817 then it would add the (1) to the chapters.

This is something I'm working on atm. Possible workarounds might be using a directory as input instead of using all files (`*`) or maybe you could try the parameter `--chapter-algo=grouping`. However, I'm trying to find a solution that fixes it instead of providing workarounds :-)

**Comment by sandreas** [comment]
@parkr 

Ok, so I found out about the Problem, why your Chapters contain ` (1)` at the end:

```
==== current tag ====
## total-duration:: 09:42:48.802
00:00:00.000 Chapter 1: The Worst Birthday (1)
00:18:31.926 Chapter 2: Dobby’s Warning (1)
00:39:36.345 Chapter 3: The Burrow (1)
...
```

It's a (really bad) mistake from the past trying to handle "sub"-chapters. Usually a chapter is a chapter, but sometimes, when a chapter is very long, it would better be broken up into "sub"-chapters to decrease the length to an amount of around 5 minutes (which I found out is almost certainly the best chapter length for quickly skimming around). 

However, when using musicbrainz without further options (like `--max-chapter-length=300,900`), it just appends ` (1)` without any further adjustments on the assumption that sub-chapters might follow. Here is an example with `--max-chapter-length=300,900`for better understanding:

```
## total-duration:: 01:56:18.931
00:00:00.000 Chapter 1: The Worst Birthday (1)
00:14:57.648 Chapter 2: Dobby’s Warning (1)
00:28:56.442 Chapter 2: Dobby’s Warning (2)
00:44:14.609 Chapter 3: The Burrow (1)
01:03:52.960 Chapter 3: The Burrow (2)
01:08:43.698 Chapter 4: At Flourish and Blotts (1)
01:24:52.113 Chapter 4: At Flourish and Blotts (2)
01:35:52.808 Chapter 4: At Flourish and Blotts (3)
01:37:47.547 Chapter 4: At Flourish and Blotts (4)
01:43:58.022 Chapter 5: The Whomping Willow (1)
```

The code reference is here: https://github.com/sandreas/m4b-tool/blob/0a47d5bd952cea53b4f0a7897668a9afc5b078cb/src/library/Chapter/ChapterMarker.php#L326

There is an option `--no-chapter-numbering`, but it's only available in the `chapters` command (not `merge`), so it will not solve the issue.

So... it's just bad old code. So bad, I did not wanna touch it, and still don't want to. It's referenced basically EVERYWHERE in the chapter logic and could break a lot of things when changed. There is no way around fixing it in the long term, but there is way more important things to do. An attempt to work around this and "doing it right" was the `--chapter-algo=grouping` thing. This is the future approach of normalizing chapters and I will refactor this part by part. 

Could you report back, if `--chapter-algo=grouping` does fix it (temporarily) for you?
