### ISSUE TITLE
chapters fails due to php permission error

### ISSUE THREAD

**Issue by glgoose** [sandreas/m4b-tool#77]
If I run m4b-tool with a folder containing a chapters.txt, it shows an error message.

OS: MacOS version 10.15.4 (19E287) [Catalina]
Command: `m4b-tool chapters TI-office-hours_23-april.m4b`
Error: 
```zsh
PHP Warning:  file_put_contents(/TI-office-hours_23-april.chapters.txt): failed to open stream: Read-only file system in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 302

Warning: file_put_contents(/TI-office-hours_23-april.chapters.txt): failed to open stream: Read-only file system in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 302
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => file_put_contents(/TI-office-hours_23-april.chapters.txt): failed to open stream: Read-only file system
    [file] => phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php
    [line] => 302
)
```

Attached files: chapters.txt, cover.jpg

**Comment by glgoose** [comment]
I tried running it with sudo and it shows a different error message now:
```zsh
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to M4bTool\Chapter\ChapterMarker::guessChaptersBySilences() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 177 and defined in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php:33
Stack trace:
#0 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(177): M4bTool\Chapter\ChapterMarker->guessChaptersBySilences(Array, Array, NULL)
#1 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(128): M4bTool\Command\ChaptersCommand->buildChapters(Array)
#2 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///u in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php on line 33

Fatal error: Uncaught TypeError: Argument 3 passed to M4bTool\Chapter\ChapterMarker::guessChaptersBySilences() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 177 and defined in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php:33
Stack trace:
#0 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(177): M4bTool\Chapter\ChapterMarker->guessChaptersBySilences(Array, Array, NULL)
#1 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(128): M4bTool\Command\ChaptersCommand->buildChapters(Array)
#2 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///u in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php on line 33
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Uncaught TypeError: Argument 3 passed to M4bTool\Chapter\ChapterMarker::guessChaptersBySilences() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 177 and defined in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php:33
Stack trace:
#0 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(177): M4bTool\Chapter\ChapterMarker->guessChaptersBySilences(Array, Array, NULL)
#1 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(128): M4bTool\Command\ChaptersCommand->buildChapters(Array)
#2 phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///u
    [file] => phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php
    [line] => 33
)
```

**Comment by sandreas** [comment]
Use the latest pre-release... it should be already fixed

**Comment by glgoose** [comment]
FIXED. Used the latest pre-release as suggested.
